spring:
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:465}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtps
    properties:
      mail:
        smtps:
          auth: true
          ssl:
            enable: true
            checkserveridentity: true
          timeout: 10000
          connectiontimeout: 10000
          writetimeout: 10000
        smtp:
          ssl:
            enable: true

management:
  health:
    mail:
      enabled: true

logging:
  level:
    org.springframework.mail: DEBUG
    org.eclipse.angus.mail: DEBUG
