spring:
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp-relay.brevo.com
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

management:
  health:
    mail:
      enabled: false

logging:
  level:
    org.springframework.mail: DEBUG
    org.eclipse.angus.mail: DEBUG
    com.example.the_guardian_v1: INFO
