spring:
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:465}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 10000
          connectiontimeout: 10000
          writetimeout: 10000
          ssl:
            checkserveridentity: true
            trust: "*"

management:
  health:
    mail:
      enabled: true # Re-enable check in prod if configured

logging:
  level:
    org.springframework.mail: DEBUG
    org.eclipse.angus.mail: DEBUG
