ALTER TABLE parents ADD COLUMN IF NOT EXISTS kyc_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE parents ADD COLUMN IF NOT EXISTS kyc_document_type VARCHAR(50);
ALTER TABLE parents ADD COLUMN IF NOT EXISTS kyc_document_number VARCHAR(50);
