org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.connectionTimeout=60000 -Dhttp.socketTimeout=60000 -Dhttp.retryHandler.requestSentRetryEnabled=true -Dnetworkaddress.cache.ttl=60 -Dnetworkaddress.cache.negative.ttl=5 -Djava.net.preferIPv4Stack=true
android.useAndroidX=true
systemProp.http.connectionTimeout=60000
systemProp.http.socketTimeout=60000
systemProp.https.connectionTimeout=60000
systemProp.https.socketTimeout=60000
systemProp.java.net.preferIPv4Stack=true