package com.example.the_guardian_v1.domain.enums;
public enum EventType {
  RULE_UPDATED, PROFILE_UPDATED, SCHEDULE_CREATED, SCHEDULE_UPDATED, SCHEDULE_DELETED,
  CONTENT_RULE_UPSERTED, KEYWORDS_REPLACED, DEVICE_EVENT_RECEIVED, EXECUTE_COMMAND_RECEIVED
}
