/// Contract shared with the parent backend Cloud Function.
///
/// Pairing tokens are opaque, URL-safe values generated by the parent app.
/// A child document id is never accepted as a pairing credential.
final RegExp pairingTokenPattern = RegExp(r'^[A-Za-z0-9_-]{32,128}$');

const Set<String> _allowedHttpsPaths = {'/child/pair', '/pair'};

String? extractPairingToken(String rawValue) {
  final trimmed = rawValue.trim();
  if (trimmed.isEmpty) return null;

  String? candidate;
  final uri = Uri.tryParse(trimmed);
  if (uri != null && uri.hasScheme) {
    final scheme = uri.scheme.toLowerCase();
    switch (scheme) {
      case 'http':
      case 'https':
        if (uri.host.toLowerCase() != 'the-guardian.app' ||
            !_allowedHttpsPaths.contains(uri.path)) {
          return null;
        }
        candidate = uri.queryParameters['code'] ?? uri.queryParameters['token'];
        break;
      case 'guardian':
        final isPairingRoute = uri.host.toLowerCase() == 'pair' ||
            (uri.host.toLowerCase() == 'child' && uri.path == '/pair');
        if (!isPairingRoute) return null;
        candidate = uri.queryParameters['code'] ?? uri.queryParameters['token'];
        break;
      default:
        return null;
    }
  } else if (!trimmed.contains(RegExp(r'[\s/]'))) {
    candidate = trimmed;
  }

  final normalized = candidate?.trim();
  if (normalized == null || !pairingTokenPattern.hasMatch(normalized)) {
    return null;
  }
  return normalized;
}
