server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/the_guardian_v1
    username: postgres
    password: "ange"
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: theguardiancontrol.app@gmail.com
    password: icnqupzwpaoesdgx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

the_guardian:
  jwt:
    secret: "CHANGE_ME_SUPER_SECRET_KEY_32CHARS_MINIMUM"
    accessTokenTtlSeconds: 3600
  execute:
    apiKey: "CHANGE_ME_EXECUTE_API_KEY"
  otp:
    expirationMinutes: 10
